# Generated by Django 3.1.5 on 2021-01-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllEc2InstanceTypes',
            fields=[
                ('instance_type', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('supported_usage_classes', models.JSONField(default=list)),
                ('virtual_cpu_info', models.JSONField(default=dict)),
                ('memory_info', models.JSONField(default=dict)),
                ('storage_info', models.JSONField(default=dict)),
                ('ebs_info', models.JSONField(default=dict)),
                ('network_info', models.JSONField(default=dict)),
                ('current_generation', models.BooleanField(default=True)),
                ('hibernation_supported', models.BooleanField(default=True)),
                ('burstable_performance_supported', models.BooleanField(default=True)),
            ],
        ),
    ]
